# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0003_pcr_result_pcr_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcr_result',
            name='RPPCR_date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
