# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0004_auto_20160913_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_reads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reads', models.IntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss.Sample')),
            ],
        ),
    ]
